# Generated by Django 5.2.8 on 2025-12-01 21:35

import django.core.validators
import django.db.models.deletion
import transparencia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Numeral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.IntegerField(
                        help_text="Número del inciso (1-29)",
                        unique=True,
                        verbose_name="Número de Inciso",
                    ),
                ),
                (
                    "titulo_corto",
                    models.CharField(max_length=200, verbose_name="Título Corto"),
                ),
                (
                    "descripcion",
                    models.TextField(
                        help_text="Descripción completa del numeral según la ley",
                        verbose_name="Descripción Legal Completa",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Se genera automáticamente del código",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarcar para ocultar este numeral del público",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "orden",
                    models.IntegerField(
                        default=0,
                        help_text="Número menor aparece primero. Por defecto usa el código",
                        verbose_name="Orden de Visualización",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Numeral (Inciso)",
                "verbose_name_plural": "Numerales (Incisos)",
                "ordering": ["orden", "codigo"],
                "indexes": [
                    models.Index(
                        fields=["codigo", "activo"],
                        name="transparenc_codigo_2e080d_idx",
                    ),
                    models.Index(fields=["orden"], name="transparenc_orden_aa9946_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Carpeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej: 2024, Enero, Febrero, Actas, Contratos, etc.",
                        max_length=100,
                        verbose_name="Nombre de la Carpeta",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Descripción opcional de esta carpeta",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "orden",
                    models.IntegerField(
                        default=0,
                        help_text="Para ordenar carpetas del mismo nivel. Usar año o mes",
                        verbose_name="Orden",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "padre",
                    models.ForeignKey(
                        blank=True,
                        help_text="Dejar vacío si es una carpeta raíz (normalmente años)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcarpetas",
                        to="transparencia.carpeta",
                        verbose_name="Carpeta Padre",
                    ),
                ),
                (
                    "numeral",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carpetas",
                        to="transparencia.numeral",
                        verbose_name="Numeral",
                    ),
                ),
            ],
            options={
                "verbose_name": "Carpeta",
                "verbose_name_plural": "Carpetas",
                "ordering": ["-orden", "-nombre"],
            },
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        help_text="Nombre descriptivo del documento",
                        max_length=300,
                        verbose_name="Título del Documento",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Descripción opcional del contenido",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        upload_to=transparencia.models.path_documento,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "xls",
                                    "xlsx",
                                    "doc",
                                    "docx",
                                    "png",
                                    "jpg",
                                    "jpeg",
                                    "svg",
                                    "csv",
                                ]
                            )
                        ],
                        verbose_name="Archivo",
                    ),
                ),
                (
                    "tamanio_bytes",
                    models.BigIntegerField(
                        default=0, editable=False, verbose_name="Tamaño en Bytes"
                    ),
                ),
                (
                    "extension",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=10,
                        verbose_name="Extensión",
                    ),
                ),
                (
                    "descargas",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Número de Descargas"
                    ),
                ),
                (
                    "publicado",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarcar para ocultar temporalmente",
                        verbose_name="Publicado",
                    ),
                ),
                (
                    "destacado",
                    models.BooleanField(
                        default=False,
                        help_text="Marcar para resaltar este documento",
                        verbose_name="Destacado",
                    ),
                ),
                (
                    "fecha_publicacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Publicación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "carpeta",
                    models.ForeignKey(
                        blank=True,
                        help_text="Seleccionar carpeta donde se publicará (opcional)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="transparencia.carpeta",
                        verbose_name="Carpeta",
                    ),
                ),
                (
                    "numeral",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="transparencia.numeral",
                        verbose_name="Numeral",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento",
                "verbose_name_plural": "Documentos",
                "ordering": ["-destacado", "-fecha_publicacion"],
                "indexes": [
                    models.Index(
                        fields=["numeral", "publicado"],
                        name="transparenc_numeral_72c4ff_idx",
                    ),
                    models.Index(
                        fields=["carpeta", "publicado"],
                        name="transparenc_carpeta_443cfb_idx",
                    ),
                    models.Index(
                        fields=["-fecha_publicacion"],
                        name="transparenc_fecha_p_29beed_idx",
                    ),
                    models.Index(
                        fields=["publicado", "-destacado"],
                        name="transparenc_publica_6a39a8_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="carpeta",
            index=models.Index(
                fields=["numeral", "padre"], name="transparenc_numeral_1750a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carpeta",
            index=models.Index(fields=["-orden"], name="transparenc_orden_e86128_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="carpeta",
            unique_together={("numeral", "nombre", "padre")},
        ),
    ]
