# Generated by Django 5.2.8 on 2025-12-23 04:28

import comude.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NumeralComude",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Ej: 01A, 01B, 29A",
                        max_length=10,
                        unique=True,
                        verbose_name="Código del Inciso",
                    ),
                ),
                (
                    "titulo_corto",
                    models.CharField(max_length=200, verbose_name="Título Corto"),
                ),
                (
                    "descripcion",
                    models.TextField(
                        help_text="Descripción del numeral",
                        verbose_name="Descripción Completa",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Se genera automáticamente",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarcar para ocultar este numeral",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "orden",
                    models.IntegerField(
                        default=0,
                        help_text="Número menor aparece primero",
                        verbose_name="Orden de Visualización",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Numeral COMUDE",
                "verbose_name_plural": "Numerales COMUDE",
                "ordering": ["orden", "codigo"],
                "indexes": [
                    models.Index(
                        fields=["codigo", "activo"],
                        name="comude_nume_codigo_dbba6f_idx",
                    ),
                    models.Index(fields=["orden"], name="comude_nume_orden_5fe121_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CarpetaComude",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej: 2024, Enero, Actas Ordinarias...",
                        max_length=100,
                        verbose_name="Nombre de la Carpeta",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("orden", models.IntegerField(default=0, verbose_name="Orden")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "padre",
                    models.ForeignKey(
                        blank=True,
                        help_text="Dejar vacío si es carpeta raíz",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcarpetas",
                        to="comude.carpetacomude",
                        verbose_name="Carpeta Padre",
                    ),
                ),
                (
                    "numeral",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carpetas",
                        to="comude.numeralcomude",
                        verbose_name="Numeral COMUDE",
                    ),
                ),
            ],
            options={
                "verbose_name": "Carpeta COMUDE",
                "verbose_name_plural": "Carpetas COMUDE",
                "ordering": ["-orden", "-nombre"],
            },
        ),
        migrations.CreateModel(
            name="DocumentoComude",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        max_length=300, verbose_name="Título del Documento"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "archivo",
                    models.FileField(
                        upload_to=comude.models.path_documento_comude,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "xls",
                                    "xlsx",
                                    "doc",
                                    "docx",
                                    "png",
                                    "jpg",
                                    "jpeg",
                                    "svg",
                                    "csv",
                                ]
                            )
                        ],
                        verbose_name="Archivo",
                    ),
                ),
                (
                    "tamanio_bytes",
                    models.BigIntegerField(
                        default=0, editable=False, verbose_name="Tamaño en Bytes"
                    ),
                ),
                (
                    "extension",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=10,
                        verbose_name="Extensión",
                    ),
                ),
                (
                    "descargas",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Número de Descargas"
                    ),
                ),
                (
                    "publicado",
                    models.BooleanField(default=True, verbose_name="Publicado"),
                ),
                (
                    "destacado",
                    models.BooleanField(default=False, verbose_name="Destacado"),
                ),
                (
                    "fecha_publicacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Publicación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "carpeta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="comude.carpetacomude",
                        verbose_name="Carpeta",
                    ),
                ),
                (
                    "numeral",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="comude.numeralcomude",
                        verbose_name="Numeral COMUDE",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento COMUDE",
                "verbose_name_plural": "Documentos COMUDE",
                "ordering": ["-destacado", "-fecha_publicacion"],
                "indexes": [
                    models.Index(
                        fields=["numeral", "publicado"],
                        name="comude_docu_numeral_578ee8_idx",
                    ),
                    models.Index(
                        fields=["carpeta", "publicado"],
                        name="comude_docu_carpeta_ce9b54_idx",
                    ),
                    models.Index(
                        fields=["-fecha_publicacion"],
                        name="comude_docu_fecha_p_480322_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="carpetacomude",
            index=models.Index(
                fields=["numeral", "padre"], name="comude_carp_numeral_138dbb_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="carpetacomude",
            unique_together={("numeral", "nombre", "padre")},
        ),
    ]
