# Generated by Django 5.2.8 on 2026-01-02 22:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SolicitudInformacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_completo",
                    models.CharField(
                        max_length=200, verbose_name="Nombres y apellidos"
                    ),
                ),
                (
                    "lugar_residencia",
                    models.CharField(
                        max_length=200, verbose_name="Lugar de residencia"
                    ),
                ),
                ("telefono", models.CharField(max_length=20, verbose_name="Teléfono")),
                (
                    "correo_electronico",
                    models.EmailField(
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="Correo electrónico",
                    ),
                ),
                (
                    "medio_entrega",
                    models.CharField(
                        choices=[
                            ("correo", "Correo electrónico"),
                            ("impreso", "Impreso"),
                            ("almacenamiento", "Dispositivo de almacenamiento"),
                        ],
                        default="correo",
                        max_length=20,
                        verbose_name="Medio de entrega",
                    ),
                ),
                (
                    "genero",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("hombre", "Hombre"),
                            ("mujer", "Mujer"),
                            ("otro", "Otro"),
                            ("prefiero_no_decir", "Prefiero no decir"),
                        ],
                        max_length=20,
                        verbose_name="Género",
                    ),
                ),
                (
                    "solicitud",
                    models.TextField(
                        help_text="Descripción clara y precisa de la información solicitada",
                        verbose_name="Solicitud",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_proceso", "En Proceso"),
                            ("respondida", "Respondida"),
                            ("rechazada", "Rechazada"),
                        ],
                        default="pendiente",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "numero_seguimiento",
                    models.CharField(
                        editable=False,
                        max_length=50,
                        unique=True,
                        verbose_name="Número de seguimiento",
                    ),
                ),
                (
                    "fecha_solicitud",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de solicitud"
                    ),
                ),
                (
                    "fecha_respuesta",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de respuesta"
                    ),
                ),
                ("respuesta", models.TextField(blank=True, verbose_name="Respuesta")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Dirección IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
            ],
            options={
                "verbose_name": "Solicitud de Información",
                "verbose_name_plural": "Solicitudes de Información",
                "ordering": ["-fecha_solicitud"],
                "indexes": [
                    models.Index(
                        fields=["-fecha_solicitud"],
                        name="solicitudes_fecha_s_e05825_idx",
                    ),
                    models.Index(
                        fields=["estado"], name="solicitudes_estado_d16fb9_idx"
                    ),
                    models.Index(
                        fields=["numero_seguimiento"],
                        name="solicitudes_numero__8a1d6a_idx",
                    ),
                ],
            },
        ),
    ]
