# Generated by Django 5.2.8 on 2025-12-29 19:09

import django.core.validators
import django.db.models.deletion
import sinacig.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarpetaSINACIG",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej: 2024, Documentos, Capacitaciones...",
                        max_length=100,
                        verbose_name="Nombre de la Carpeta",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("documentos", "Documentos"),
                            ("unidades", "Unidades"),
                            ("capacitaciones", "Capacitaciones"),
                            ("acuerdos", "Acuerdos"),
                        ],
                        help_text="Solo para carpetas de segundo nivel",
                        max_length=20,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("orden", models.IntegerField(default=0, verbose_name="Orden")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "padre",
                    models.ForeignKey(
                        blank=True,
                        help_text="Dejar vacío si es carpeta raíz (año)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcarpetas",
                        to="sinacig.carpetasinacig",
                        verbose_name="Carpeta Padre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Carpeta SINACIG",
                "verbose_name_plural": "Carpetas SINACIG",
                "ordering": ["-orden", "-nombre"],
            },
        ),
        migrations.CreateModel(
            name="DocumentoSINACIG",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        max_length=300, verbose_name="Título del Documento"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "archivo",
                    models.FileField(
                        upload_to=sinacig.models.path_documento_sinacig,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "xls",
                                    "xlsx",
                                    "doc",
                                    "docx",
                                    "png",
                                    "jpg",
                                    "jpeg",
                                    "svg",
                                    "csv",
                                ]
                            )
                        ],
                        verbose_name="Archivo",
                    ),
                ),
                (
                    "tamanio_bytes",
                    models.BigIntegerField(
                        default=0, editable=False, verbose_name="Tamaño en Bytes"
                    ),
                ),
                (
                    "extension",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=10,
                        verbose_name="Extensión",
                    ),
                ),
                (
                    "descargas",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Número de Descargas"
                    ),
                ),
                (
                    "publicado",
                    models.BooleanField(default=True, verbose_name="Publicado"),
                ),
                (
                    "destacado",
                    models.BooleanField(default=False, verbose_name="Destacado"),
                ),
                (
                    "fecha_publicacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Publicación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "carpeta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="sinacig.carpetasinacig",
                        verbose_name="Carpeta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento SINACIG",
                "verbose_name_plural": "Documentos SINACIG",
                "ordering": ["-destacado", "-fecha_publicacion"],
            },
        ),
        migrations.AddIndex(
            model_name="carpetasinacig",
            index=models.Index(
                fields=["padre", "categoria"], name="sinacig_car_padre_i_25d57b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carpetasinacig",
            index=models.Index(fields=["orden"], name="sinacig_car_orden_69d789_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="carpetasinacig",
            unique_together={("nombre", "padre")},
        ),
        migrations.AddIndex(
            model_name="documentosinacig",
            index=models.Index(
                fields=["carpeta", "publicado"], name="sinacig_doc_carpeta_1416a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentosinacig",
            index=models.Index(
                fields=["-fecha_publicacion"], name="sinacig_doc_fecha_p_33a222_idx"
            ),
        ),
    ]
